<?php
define('NOMBRE_SISTEMA', 'LATINOTOURS');
define('DOCUMENTO_EMPRESA_E', '20611371633');
define('RAZON_SOCIAL_E', 'LLATINO TOURS S.A.C.');
define('NOMBRE_COMERCIAL_E', 'LLATINO TOURS S.A.C.');
define('CODIGO_UBIGEO_E', "250101");
define('DIRECCION_E', "JR. LIBERTAD NRO. 378 (CERCA AL JIRON LIBERTAD) HUANUCO - HUAMALIES - LLATA");
define('DIRECCION_E_COMPROBANTE', "JR. LIBERTAD NRO. 378 (CERCA AL JIRON LIBERTAD) HUANUCO - HUAMALIES - LLATA");
define('DEPARTAMENTO_E', "HUANUCO");
define('PROVINCIA_E', "HUAMALIES");
define('DISTRITO_E', "LLATA");
define('TELEFONOS_E', "");
define('CODIGO_PAIS_E', 'PE');
define('USUARIO_SOL_E', 'LLATINOT'); // cambiar cuando se pase a produccion //NEURO123
define('PASS_SOL_E', 'LL4T1N0t'); // cambiar cuando se pase a produccion
?>