<?php
define('NOMBRE_SISTEMA', 'FISEL');
define('DOCUMENTO_EMPRESA_E', '10728906915');
define('RAZON_SOCIAL_E', 'FERRETERIA INDUSTRIAL SELVA E.I.R.L.');
define('NOMBRE_COMERCIAL_E', 'FERRETERIA INDUSTRIAL SELVA E.I.R.L.');
define('CODIGO_UBIGEO_E', "250101");
define('DIRECCION_E', "JR. ZAVALA NRO. 621 (COSTADO DE SUCURSAL DEL BANCO DE CREDITO) UCAYALI - CORONEL PORTILLO - CALLERIA");
define('DIRECCION_E_COMPROBANTE', "JR. ZAVALA NRO. 621 <br> (COSTADO DE SUCURSAL DEL BANCO DE CREDITO)");
define('DEPARTAMENTO_E', "UCAYALI");
define('PROVINCIA_E', "PORTILLO");
define('DISTRITO_E', "CALLERIA");
define('TELEFONOS_E', "");
define('CODIGO_PAIS_E', 'PE');
define('USUARIO_SOL_E', 'CAMBIAR'); // cambiar cuando se pase a produccion //NEURO123
define('PASS_SOL_E', 'CAMBIAR'); // cambiar cuando se pase a produccion
?>